datasets:
  save_data: True
  batch_size: 1
  # data_paths:
  #   train: train.xyz
  labels:
    scalar:
      energy: energy
    vector:
      charges: decomposed_charges
      forces: forces
      magmoms: decomposed_magmoms
  val_split: 0.2
general:
  logs_dir: logs
  logs_lev: 20
  models_dir: checkpoints
  name: LEOPOLD
  result_dir: results
  seed: 42
  use_float64: true
model:
  even_act: sigmoid
  even_gate: gelu
  hidden_irr: 48x0e + 48x1e
  n_basis: 8
  n_convo: 2
  n_harmo: 2
  n_neighbour: 1.0
  odd_act: tanh
  odd_gate: soft
  r_cutoff: 3.5
  radial_mlp_activa: swish
  radial_mlp_hidden: 64
  radial_mlp_layers: 2
training:
  smagmo_weight: 1.0
  magmom_weight: 1.0
  charge_weight: 1.0
  energy_weight: 1.0
  forces_weight: 1.0
  learning_rate: 0.0005
  max_epoch: 1000
  patience: 200
