datasets:
  data_paths:
    train: "train.xyz"
  labels:
    scalar:
      energy: energy
    vector:
      charges: decomposed_charges
      forces: forces
      magmoms: decomposed_magmoms
  save_data: true
  val_split: 0.20
general:
  checkpoint_file: LEOPOLD-42.h5
  logs_dir: logs
  logs_lev: 20
  models_dir: checkpoints
  name: LEOPOLD
  result_dir: results
  seed: 42
  use_float64: false
model:
  even_act: sigmoid
  even_gate: gelu
  hidden_irr: 8x0e + 8x1e
  n_basis: 8
  n_convo: 1
  n_harmo: 2
  odd_act: tanh
  odd_gate: soft
  r_cutoff: 3.5
  radial_mlp_activa: swish
  radial_mlp_hidden: 10
  radial_mlp_layers: 1
training:
  batch_size: 1
  charge_weight: 1.0
  energy_weight: 1.0
  forces_weight: 1.0
  learning_rate: 0.0005
  magmom_weight: 1.0
  max_epoch: 1000
  patience: 200
  restart: true
  smagmo_weight: 1.0
