"""
Module containing the H5MD file specifications for the LEOPOLD module

creation: 2025-03-05 15:37:29
author:   Luca Leoni
contact:  luca.leoni12@unibo.it
"""

# ==== DEPENDENCIES ==== #

# Math
import numpy as np

# H5
import h5py

# Types
from h5py import File, Group, Dataset
from enum import Enum, unique
from ase import Atoms

# Version
from __init__ import __version__

# ==== OBJECTS ==== #


@unique
class SimType(Enum):
    NVE = 0
    NVT = 1
    NPT = 2


class LeopoldH5MD(File):
    particles: Group
    observables: Group

    def __init__(
        self, name, mode, author_name: str = "N/A", email: str = "N/A", *args, **kwargs
    ):
        super(LeopoldH5MD, self).__init__(name, mode, *args, **kwargs)

        if "w" in mode:
            # Construct metadata

            # Version and Creation
            g = self.create_group("h5md")
            g.attrs["version"] = "1.1"
            g.attrs["creation"] = str(np.datetime_as_string(np.datetime64("now"), "s"))

            # Specifics for saing it's a LEOPOLD H5MD file
            g = self.create_group("h5md/creator")
            g.attrs["name"] = "leopold"
            g.attrs["version"] = __version__

            # Author of the document
            g = self.create_group("h5md/author")
            g.attrs["name"] = author_name
            g.attrs["email"] = email
        else:
            # Look if h5md file
            if "h5md" not in self:
                raise KeyError("h5md group not found in file")
            g = Group(self["h5md"])

            # Look if created through LEOPOLD
            if not g["creator"].attrs["name"] == "leopold":
                raise ValueError("This h5md file was not generated by Leopold")

    def attach_simulation(
        self, start_config: Atoms, sim_type: SimType = SimType.NPT, compression: int = 5
    ) -> None:
        pass


# ==== MAIN ==== #
if __name__ == "__main__":
    with LeopoldH5MD("test.h5", "w") as f:
        pass
