"""
Module containing the HDF5 file specifications for the LEOPOLD module

creation: 2025-03-05 15:37:29
author:   Luca Leoni
contact:  luca.leoni12@unibo.it
"""

# ==== DEPENDENCIES ==== #

# Math
import numpy as np

# ASE
from ase import Atoms

# H5
from h5py import File, Group

# Leopold
from .dataset import (
    LeopoldDataLoader,
    leopold_dataloader_to_hdf5,
    save_dictionary_to_hdf5,
)

# Types
from enum import Enum, unique

# Warnings
import warnings

# Version
from .__init__ import __version__

# ==== ARCHETIPE FILE ==== #


class LeopoldHDF5(File):
    def __init__(
        self, name, mode, author_name: str = "N/A", email: str = "N/A", *args, **kwargs
    ):
        super(LeopoldHDF5, self).__init__(name, mode, *args, **kwargs)

        if "w" in mode:
            # Specifics for saing it's a LEOPOLD HDF5 file
            g = self.create_group("creator")
            g.attrs["name"] = "leopold"
            g.attrs["version"] = __version__
            g.attrs["date"] = np.datetime64("today")

            # Author of the document
            g = self.create_group("author")
            g.attrs["name"] = author_name
            g.attrs["email"] = email
        else:
            if "creator" not in self:
                raise KeyError("creator group not found in file")
            g = Group(self["creator"].id)

            # Look if created through LEOPOLD
            if not g["creator"].attrs["name"] == "leopold":
                raise ValueError("this hdf5 file was not generated by Leopold")

            # Look version mistmatch
            if g.attrs["version"] != __version__:
                warnings.warn("this hdf5 leopold file and module versions mismatch")

        # Add last modification attributes
        if "w" in mode or "a" in mode:
            self["creator"].attrs["modified"] = np.datetime64("now")


# ==== ML STATE ==== #


class LeopoldCheckpointFile(LeopoldHDF5):
    datasets: Group
    training: Group
    models: Group

    def __init__(
        self,
        name,
        mode,
        conf: dict,
        author_name: str = "N/A",
        email: str = "N/A",
        *args,
        **kwargs,
    ):
        super(LeopoldCheckpointFile, self).__init__(
            name, mode, author_name, email, *args, **kwargs
        )

        # Create dataset group
        self.datasets = self.require_group("datasets")

        # Create training group with specifics
        # TODO: possibility of adding multiple trainings?
        self.training = self.require_group("training")

        g = self.training.require_group("specifics")
        save_dictionary_to_hdf5(g, conf["training"])

        # Create model group with model specifics
        self.models = self.require_group("models")

        g = self.models.require_group("specifics")
        save_dictionary_to_hdf5(g, conf["model"])

    def write_dataset(self, name: str, loader: LeopoldDataLoader) -> None:
        g = self.datasets.require_group(name)
        leopold_dataloader_to_hdf5(g, loader)

    def write_model(self, name: str, params: dict) -> None:
        g = self.models.require_group(name)
        save_dictionary_to_hdf5(g, params)

    def write_opt_state(self, name: str, state: dict) -> None:
        g = self.training.require_group(name)
        save_dictionary_to_hdf5(g, state)


# ==== H5MD FILE ==== #


@unique
class SimType(Enum):
    NVE = 0
    NVT = 1
    NPT = 2


class LeopoldH5MD(File):
    particles: Group
    observables: Group

    def __init__(
        self, name, mode, author_name: str = "N/A", email: str = "N/A", *args, **kwargs
    ):
        super(LeopoldH5MD, self).__init__(name, mode, *args, **kwargs)

        if "w" in mode:
            # Construct metadata

            # Version and Creation
            g = self.create_group("h5md")
            g.attrs["version"] = "1.1"
            g.attrs["creation"] = str(np.datetime_as_string(np.datetime64("now"), "s"))

            # Specifics for saing it's a LEOPOLD H5MD file
            g = self.create_group("h5md/creator")
            g.attrs["name"] = "leopold"
            g.attrs["version"] = __version__

            # Author of the document
            g = self.create_group("h5md/author")
            g.attrs["name"] = author_name
            g.attrs["email"] = email
        else:
            # Look if h5md file
            if "h5md" not in self:
                raise KeyError("h5md group not found in file")
            g = Group(self["h5md"])

            # Look if created through LEOPOLD
            if not g["creator"].attrs["name"] == "leopold":
                raise ValueError("This h5md file was not generated by Leopold")

    def attach_simulation(
        self, start_config: Atoms, sim_type: SimType = SimType.NPT, compression: int = 5
    ) -> None:
        pass


# ==== MAIN ==== #
if __name__ == "__main__":
    with LeopoldH5MD("test.h5", "w") as f:
        pass
