"""
Module containing the HDF5 file specifications for the LEOPOLD module

creation: 2025-03-05 15:37:29
author:   Luca Leoni
contact:  luca.leoni12@unibo.it
"""

# ==== DEPENDENCIES ==== #

# Math
import numpy as np

# ASE
from ase import Atoms

# H5
from h5py import File, Group, Dataset

# Cuequivariance
from cuequivariance_jax import RepArray

# Jax
import jax
from jax import Device

# Leopold
from .dataset import (
    Configuration,
    Labels,
    LeopoldData,
    LeopoldDataInfo,
    LeopoldDataLoader,
)

from .config import (
    LeopoldConfiguration,
    LeopoldDatasetsOptions,
    LeopoldGeneralOptions,
    LeopoldTrainingOptions,
)

# Types
from dataclasses import asdict
from enum import Enum, unique
from typing import Optional, override

# Warnings
import warnings

# Version
from .__init__ import __version__

# ==== FUNCTIONS ==== #


def save_dictionary_to_hdf5(group: Group, data: dict, compression: int = 9) -> None:
    for key, value in data.items():
        if isinstance(value, dict):
            save_dictionary_to_hdf5(group.require_group(key), value)
        else:
            # Handle RepArray
            if isinstance(value, RepArray):
                arr = np.asarray(value.array)

                d = group.require_dataset(
                    key, arr.shape, arr.dtype, compression=compression
                )

                # Save irreps as attributes
                d.attrs["Irreps"] = str(value.irreps)
                d[:] = arr
            else:
                # Deal with null data
                if value is None:
                    group.require_dataset(key, shape=None, dtype="f")
                    continue

                # Handle scalars
                if np.isscalar(value):
                    group.require_dataset(key, shape=(), dtype=type(value))[()] = value
                    continue

                # Handle real array
                value = np.asarray(value)

                # Deal with empty dataset
                if value.shape == ():
                    group.require_dataset(key, shape=None, dtype="f")
                else:
                    group.require_dataset(
                        key, value.shape, value.dtype, compression=compression
                    )[:] = value


# ==== ARCHETIPE FILE ==== #


class LeopoldHDF5(File):
    def __init__(
        self, name, mode, author_name: str = "N/A", email: str = "N/A", *args, **kwargs
    ):
        super(LeopoldHDF5, self).__init__(name, mode, *args, **kwargs)

        if "w" in mode:
            # Specifics for saing it's a LEOPOLD HDF5 file
            g = self.create_group("creator")
            g.attrs["name"] = "leopold"
            g.attrs["version"] = __version__
            g.attrs["date"] = str(np.datetime64("today"))

            # Author of the document
            g = self.create_group("author")
            g.attrs["name"] = author_name
            g.attrs["email"] = email
        else:
            if "creator" not in self:
                raise KeyError("creator group not found in file")
            g = Group(self["creator"].id)

            # Look if created through LEOPOLD
            if not g.attrs["name"] == "leopold":
                raise ValueError("this hdf5 file was not generated by Leopold")

            # Look version mistmatch
            if g.attrs["version"] != __version__:
                warnings.warn("this hdf5 leopold file and module versions mismatch")

        # Add last modification attributes
        if "w" in mode or "a" in mode:
            self["creator"].attrs["modified"] = str(np.datetime64("now"))


# ==== General Group ==== #


class LeopoldDatasetGroup:
    def __init__(self, group: Group):
        # Start as empty
        self.__empty

        # Set variables
        self.__group = group
        self.__config = group.require_group("configurations")
        self.__labels = group.require_group("labels")

        # See if it's empty
        try:
            len(Dataset(self.__config["positions"].id))
        except TypeError:
            self.__empty = True

    def __getitem__(self, idx) -> LeopoldData:
        assert not self.__empty, "tried to index an empty LeopoldDataGroup!"

        # Collect real data
        config, labels = {}, {}

        # Get configurations data
        for key in self.__config:
            d = Dataset(self.__config[key].id)

            # If dataset id empty set empty
            if d.shape is None:
                config[key] = None
                continue

            config[key] = d[idx]

        # Get labels data
        for key in self.__labels:
            d = Dataset(self.__labels[key].id)

            # If dataset id empty set empty
            if d.shape is None:
                config[key] = None
                continue

            config[key] = d[idx]

        config = Configuration(**config)
        labels = Labels(**labels)

        return LeopoldData(config, labels)

    @property
    def group(self) -> Group:
        return self.__group

    @property
    def info(self) -> LeopoldDataInfo:
        info = self.__group.attrs.__dict__.copy()

        return LeopoldDataInfo(**info)

    def write_dataloader(
        self,
        loader: LeopoldDataLoader,
        save_data: bool = True,
        compression: int = 9,
    ) -> None:
        # First write down the info
        for key, val in asdict(loader.info).items():
            self.__group.attrs[key] = val

        # Save data
        if save_data:
            # If wanted save all
            config = loader.data.config._asdict()
            labels = loader.data.labels._asdict()
        else:
            # If not use empty arrays
            config = {k: None for k in loader.data.config._asdict().keys()}
            labels = {k: None for k in loader.data.labels._asdict().keys()}

        # Save it on HDF5
        save_dictionary_to_hdf5(self.__config, config, compression)
        save_dictionary_to_hdf5(self.__labels, labels, compression)

        # Set as not empty
        self.__empty = False

    def get_dataloader(
        self,
        batch_size: int = 1,
        device: Device = jax.devices("cuda")[0],
    ) -> LeopoldDataLoader:
        assert not self.__empty, (
            "tried to create a data loader from an empty LeopoldDataGroup!"
        )

        return LeopoldDataLoader(
            self[()], info=self.info, batch_size=batch_size, device=device
        )


class LeopoldTrainingGroup:
    def __init__(
        self,
        group: Group,
        train_data: Optional[LeopoldDatasetGroup] = None,
        valid_data: Optional[LeopoldDatasetGroup] = None,
        test_data: Optional[LeopoldDatasetGroup] = None,
    ) -> None:
        self.__group = group

        self.__last_model = group.require_group("last_model")
        self.__last_state = group.require_group("last_state")

        if train_data is not None:
            group["train_data"] = train_data.group
        elif "train_data" not in group.keys():
            raise KeyError(f"no training data group provided to training {group.name}")

        if valid_data is not None:
            group["valid_data"] = valid_data.group

        if test_data is not None:
            group["test_data"] = test_data.group

    @property
    def info(self) -> LeopoldTrainingOptions:
        return LeopoldTrainingOptions(**self.__group.__dict__)

    @info.setter
    def info(self, info: LeopoldTrainingOptions) -> None:
        for key, val in asdict(info):
            self.__group.attrs[key] = val


# ==== ML STATE ==== #


class LeopoldCheckpointFile(LeopoldHDF5):
    datasets: Group
    training: Group
    models: Group

    def __init__(
        self,
        name,
        mode,
        author_name: str = "N/A",
        email: str = "N/A",
        *args,
        **kwargs,
    ):
        super(LeopoldCheckpointFile, self).__init__(
            name, mode, author_name, email, *args, **kwargs
        )

        # Create dataset group
        self.datasets = self.require_group("datasets")

        # Create training group with specifics
        # TODO: possibility of adding multiple trainings?
        self.training = self.require_group("trainings")

        # Create model group with model specifics
        self.models = self.require_group("models")

    def get_datasets(self) -> dict[str, LeopoldDataLoader]:
        data = {}

        for key in self.datasets.keys():
            data[key] = LeopoldDatasetGroup(
                self.datasets.require_group(key)
            ).get_dataloader()

        return data

    def write_dataset(
        self, name: str, loader: LeopoldDataLoader, save_data: bool = True
    ) -> None:
        g = self.datasets.require_group(name)
        leopold_dataloader_to_hdf5(g, loader, save_data)

    def write_model(
        self,
        name: str,
        params: dict,
    ) -> None:
        g = self.models.require_group(name)
        save_dictionary_to_hdf5(g, params)

    def write_opt_state(self, name: str, state: dict) -> None:
        g = self.training.require_group(name)
        save_dictionary_to_hdf5(g, state)


# ==== H5MD FILE ==== #


@unique
class SimType(Enum):
    NVE = 0
    NVT = 1
    NPT = 2


class LeopoldH5MD(File):
    particles: Group
    observables: Group

    def __init__(
        self, name, mode, author_name: str = "N/A", email: str = "N/A", *args, **kwargs
    ):
        super(LeopoldH5MD, self).__init__(name, mode, *args, **kwargs)

        if "w" in mode:
            # Construct metadata

            # Version and Creation
            g = self.create_group("h5md")
            g.attrs["version"] = "1.1"
            g.attrs["creation"] = str(np.datetime_as_string(np.datetime64("now"), "s"))

            # Specifics for saing it's a LEOPOLD H5MD file
            g = self.create_group("h5md/creator")
            g.attrs["name"] = "leopold"
            g.attrs["version"] = __version__

            # Author of the document
            g = self.create_group("h5md/author")
            g.attrs["name"] = author_name
            g.attrs["email"] = email
        else:
            # Look if h5md file
            if "h5md" not in self:
                raise KeyError("h5md group not found in file")
            g = Group(self["h5md"])

            # Look if created through LEOPOLD
            if not g["creator"].attrs["name"] == "leopold":
                raise ValueError("This h5md file was not generated by Leopold")

    def attach_simulation(
        self, start_config: Atoms, sim_type: SimType = SimType.NPT, compression: int = 5
    ) -> None:
        pass


# ==== MAIN ==== #
if __name__ == "__main__":
    with LeopoldH5MD("test.h5", "w") as f:
        pass
